import { Ingredient, Recipe } from './types';

// Konstanten für normale Makronährstoff- und Kalorienziele
const PROTEIN_TARGET = 150; // Protein in Gramm pro Tag
const CARBS_TARGET = 265; // Kohlenhydrate in Gramm pro Tag
const FAT_TARGET = 60; // Fett in Gramm pro Tag

// Hard-gecodete Rezepte als Beispiele
// Zutaten
const ingredients: Record<string, Ingredient> = {
    champignon: {
        id: 'champignon',
        name: 'Champignons weiß',
        category: 'Gemüse',
        isFlexible: true,
        macrosPer100g: { protein: 3.8, carbs: 2.7, fat: 0.2 },
    },
    egg: {
        id: 'egg',
        name: 'Ei',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 11.9, carbs: 1.5, fat: 9.3 },
    },
    mincedBeef: {
        id: 'mincedBeef',
        name: 'Hackfleisch Rind 5%',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 21.0, carbs: 0.0, fat: 5.0 },
    },
    oats: {
        id: 'oats',
        name: 'Haferflocken',
        category: 'Kohlenhydrate',
        isFlexible: true,
        macrosPer100g: { protein: 13.5, carbs: 58.7, fat: 7.0 },
    },
    chickenBreast: {
        id: 'chickenBreast',
        name: 'Hähnchenbrustfilet',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 23.0, carbs: 0.0, fat: 1.1 },
    },
    raspberry: {
        id: 'raspberry',
        name: 'Himbeeren',
        category: 'Obst',
        isFlexible: true,
        macrosPer100g: { protein: 1.3, carbs: 4.8, fat: 0.3 },
    },
    yoghurt15: {
        id: 'yoghurt15',
        name: 'Joghurt (1,5%)',
        category: 'Milchprodukte',
        isFlexible: true,
        macrosPer100g: { protein: 4.5, carbs: 3.9, fat: 1.5 },
    },
    carrot: {
        id: 'carrot',
        name: 'Karotten',
        category: 'Gemüse',
        isFlexible: true,
        macrosPer100g: { protein: 1.0, carbs: 4.8, fat: 0.2 },
    },
    potato: {
        id: 'potato',
        name: 'Kartoffeln',
        category: 'Kohlenhydrate',
        isFlexible: true,
        macrosPer100g: { protein: 2.0, carbs: 14.6, fat: 0.1 },
    },
    cheeseLight: {
        id: 'cheeseLight',
        name: 'Käse (Light 17%)',
        category: 'Milchprodukte',
        isFlexible: true,
        macrosPer100g: { protein: 29.0, carbs: 0.1, fat: 17.0 },
    },
    quark: {
        id: 'quark',
        name: 'Magerquark',
        category: 'Milchprodukte',
        isFlexible: true,
        macrosPer100g: { protein: 12.0, carbs: 4.1, fat: 0.2 },
    },
    milk15: {
        id: 'milk15',
        name: 'Milch (1,5%)',
        category: 'Milchprodukte',
        isFlexible: true,
        macrosPer100g: { protein: 3.4, carbs: 4.9, fat: 1.5 },
    },
    milk35: {
        id: 'milk35',
        name: 'Milch (3,5%)',
        category: 'Milchprodukte',
        isFlexible: true,
        macrosPer100g: { protein: 3.4, carbs: 4.7, fat: 3.5 },
    },
    mozzarellaLight: {
        id: 'mozzarellaLight',
        name: 'Mozzarella (Light)',
        category: 'Milchprodukte',
        isFlexible: true,
        macrosPer100g: { protein: 19.0, carbs: 1.0, fat: 8.5 },
    },
    oliveoil: {
        id: 'oliveoil',
        name: 'Olivenöl',
        category: 'Fette',
        isFlexible: true,
        macrosPer100g: { protein: 0.0, carbs: 0.0, fat: 91.5 },
    },
    paprikaRed: {
        id: 'paprikaRed',
        name: 'Paprika, rot',
        category: 'Gemüse',
        isFlexible: true,
        macrosPer100g: { protein: 1.3, carbs: 6.4, fat: 0.5 },
    },
    turkeyBreast: {
        id: 'turkeyBreast',
        name: 'Putenbrustaufschnitt',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 19.7, carbs: 1.0, fat: 2.0 },
    },
    quinoa: {
        id: 'quinoa',
        name: 'Quinoa',
        category: 'Kohlenhydrate',
        isFlexible: true,
        macrosPer100g: { protein: 12.0, carbs: 62.0, fat: 5.9 },
    },
    beefSteak: {
        id: 'beefSteak',
        name: 'Rindersteak',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 21.0, carbs: 1.5, fat: 5.0 },
    },
    rice: {
        id: 'rice',
        name: 'Reis (Basmati)',
        category: 'Kohlenhydrate',
        isFlexible: true,
        macrosPer100g: { protein: 9.0, carbs: 78.6, fat: 0.3 },
    },
    riceCake: {
        id: 'riceCake',
        name: 'Reiswaffel',
        category: 'Kohlenhydrate',
        isFlexible: true,
        macrosPer100g: { protein: 7.8, carbs: 80.6, fat: 3.0 },
    },
    skyr: {
        id: 'skyr',
        name: 'Skyr',
        category: 'Milchprodukte',
        isFlexible: true,
        macrosPer100g: { protein: 11.0, carbs: 4.0, fat: 0.2 },
    },
    spinach: {
        id: 'spinach',
        name: 'Spinat',
        category: 'Gemüse',
        isFlexible: true,
        macrosPer100g: { protein: 2.9, carbs: 1.4, fat: 0.4 },
    },
    sweetPotato: {
        id: 'sweetPotato',
        name: 'Süßkartoffeln',
        category: 'Kohlenhydrate',
        isFlexible: true,
        macrosPer100g: { protein: 1.6, carbs: 20.0, fat: 0.1 },
    },
    salmon: {
        id: 'salmon',
        name: 'Lachsfilet',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 20.0, carbs: 23.4, fat: 25.0 }, // Beachte: Die Werte in der Tabelle sind vermutlich vertauscht, ggf. anpassen!
    },
    tuna: {
        id: 'tuna',
        name: 'Thunfisch (Eigensaft)',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 25.0, carbs: 0.6, fat: 0.5 },
    },
    walnuts: {
        id: 'walnuts',
        name: 'Walnüsse',
        category: 'Fette',
        isFlexible: true,
        macrosPer100g: { protein: 15.3, carbs: 6.3, fat: 66.3 },
    },
    whey: {
        id: 'whey',
        name: 'Whey',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 74.0, carbs: 5.8, fat: 2.7 },
    },
    wheyIsolate: {
        id: 'wheyIsolate',
        name: 'Whey Isolat',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 85.0, carbs: 3.7, fat: 0.9 },
    },
    wildSalmon: {
        id: 'wildSalmon',
        name: 'Wildlachsfilet',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 21.0, carbs: 0.0, fat: 1.0 },
    },
    proteinPudding: {
        id: 'proteinPudding',
        name: 'Protein Pudding',
        category: 'Milchprodukte',
        isFlexible: true,
        macrosPer100g: { protein: 10.0, carbs: 5.2, fat: 1.5 },
    },
    cottageCheese: {
        id: 'cottageCheese',
        name: 'Körniger Frischkäse light',
        category: 'Milchprodukte',
        isFlexible: true,
        macrosPer100g: { protein: 12.5, carbs: 3.1, fat: 0.8 },
    },
    kaisergemuese: {
        id: 'kaisergemuese',
        name: 'Kaisergemüse',
        category: 'Gemüse',
        isFlexible: true,
        macrosPer100g: { protein: 2.5, carbs: 5.1, fat: 0.5 },
    },
    fetaLight: {
        id: 'fetaLight',
        name: 'Feta light',
        category: 'Milchprodukte',
        isFlexible: true,
        macrosPer100g: { protein: 19.0, carbs: 0.9, fat: 9.0 },
    },
    proteinDrinkLidl: {
        id: 'proteinDrinkLidl',
        name: 'Protein Drink Lidl',
        category: 'Milchprodukte',
        isFlexible: true,
        macrosPer100g: { protein: 10.5, carbs: 5.5, fat: 0.2 },
    },
    ramaCremfine: {
        id: 'ramaCremfine',
        name: 'Rama Cremfine 7%',
        category: 'Fette',
        isFlexible: true,
        macrosPer100g: { protein: 1.0, carbs: 4.5, fat: 7.0 },
    },
    shrimp: {
        id: 'shrimp',
        name: 'Garnelen',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 22.0, carbs: 0.5, fat: 0.5 },
    },
    coconutMilkLight: {
        id: 'coconutMilkLight',
        name: 'Kokosmilch light',
        category: 'Fette',
        isFlexible: true,
        macrosPer100g: { protein: 1.1, carbs: 1.6, fat: 12.0 },
    },
    proteinMuesli: {
        id: 'proteinMuesli',
        name: 'Protein Müsli Vitalis',
        category: 'Kohlenhydrate',
        isFlexible: true,
        macrosPer100g: { protein: 30.0, carbs: 25.0, fat: 19.0 },
    },
    likeDoener: {
        id: 'likeDoener',
        name: 'Like Döner',
        category: 'Protein',
        isFlexible: true,
        macrosPer100g: { protein: 18.0, carbs: 0.0, fat: 3.7 },
    },
    berryMix: {
        id: 'berryMix',
        name: 'Beerenmix',
        category: 'Obst',
        isFlexible: true,
        macrosPer100g: { protein: 1.1, carbs: 5.8, fat: 0.1 },
    },
    redLentilPasta: {
        id: 'redLentilPasta',
        name: 'Rote Linsennudeln',
        category: 'Kohlenhydrate',
        isFlexible: true,
        macrosPer100g: { protein: 26.0, carbs: 49.0, fat: 1.4 },
    },
    broccoli: {
        id: 'broccoli',
        name: 'Brokkoli',
        category: 'Gemüse',
        isFlexible: true,
        macrosPer100g: { protein: 3.8, carbs: 2.9, fat: 0.2 },
    },
    gnocchi: {
        id: 'gnocchi',
        name: 'Gnocchi',
        category: 'Kohlenhydrate',
        isFlexible: true,
        macrosPer100g: { protein: 2.8, carbs: 31.0, fat: 1.0 },
    },
    proteinWrap: {
        id: 'proteinWrap',
        name: 'Protein Wrap',
        category: 'Kohlenhydrate',
        isFlexible: true,
        macrosPer100g: { protein: 18.0, carbs: 39.0, fat: 8.7 },
    },
    tomatoPassata: {
        id: 'tomatoPassata',
        name: 'Passierte Tomaten',
        category: 'Gemüse',
        isFlexible: true,
        macrosPer100g: { protein: 1.6, carbs: 5.6, fat: 0.3 },
    },
    zucchini: {
        id: 'zucchini',
        name: 'Zucchini',
        category: 'Gemüse',
        isFlexible: true,
        macrosPer100g: { protein: 1.2, carbs: 2.2, fat: 0.2 }, // Wert geschätzt, da nicht in der Tabelle
    },
};

// Beispiel-Rezepte
export const recipes: Record<string, Recipe> = {
    breakfastBowl: {
        id: 'breakfast_bowl',
        name: 'Frühstücksbowl',
        ingredients: [
            { ingredient: ingredients.skyr, amount: 250 },
            { ingredient: ingredients.walnuts, amount: 30 },
            { ingredient: ingredients.berryMix, amount: 200 },
        ],
    },
    omelette: {
        id: 'omelette',
        name: 'Omlette',
        ingredients: [
            { ingredient: ingredients.egg, amount: 3 * 60 }, // 3 Eier à ~60g
            { ingredient: ingredients.paprikaRed, amount: 100 },
            { ingredient: ingredients.oliveoil, amount: 5 },
            { ingredient: ingredients.turkeyBreast, amount: 50 },
        ],
    },
    chickenPotatoVeg: {
        id: 'chicken_potato_veg',
        name: 'Hähnchen mit Kartoffeln und Kaisergemüse',
        ingredients: [
            { ingredient: ingredients.chickenBreast, amount: 200 },
            { ingredient: ingredients.potato, amount: 200 },
            { ingredient: ingredients.kaisergemuese, amount: 300 },
            { ingredient: ingredients.oliveoil, amount: 5 },
        ],
    },
    beefRiceChampignon: {
        id: 'beef_rice_champignon',
        name: 'Rindersteak mit Reis und Champignons',
        ingredients: [
            { ingredient: ingredients.beefSteak, amount: 200 },
            { ingredient: ingredients.rice, amount: 125 },
            { ingredient: ingredients.champignon, amount: 150 },
            { ingredient: ingredients.ramaCremfine, amount: 125 },
            { ingredient: ingredients.oliveoil, amount: 5 },
        ],
    },
    tunaQuinoaZucchini: {
        id: 'tuna_quinoa_zucchini',
        name: 'Thunfisch mit Quinoa und Zucchini',
        ingredients: [
            { ingredient: ingredients.tuna, amount: 150 },
            { ingredient: ingredients.quinoa, amount: 150 },
            { ingredient: ingredients.zucchini, amount: 150 },
            { ingredient: ingredients.oliveoil, amount: 5 },
        ],
    },
    mincedBeefRicePaprika: {
        id: 'mincedbeef_rice_paprika',
        name: 'Hackfleisch mit Reis und Paprika',
        ingredients: [
            { ingredient: ingredients.mincedBeef, amount: 150 },
            { ingredient: ingredients.rice, amount: 125 },
            { ingredient: ingredients.paprikaRed, amount: 100 },
            { ingredient: ingredients.oliveoil, amount: 5 },
        ],
    },
    chickenRiceBroccoli: {
        id: 'chicken_rice_broccoli',
        name: 'Hähnchen mit Reis und Brokkoli',
        ingredients: [
            { ingredient: ingredients.chickenBreast, amount: 200 },
            { ingredient: ingredients.rice, amount: 125 },
            { ingredient: ingredients.broccoli, amount: 300 },
            { ingredient: ingredients.oliveoil, amount: 5 },
        ],
    },
    wildSalmonSweetPotatoBroccoli: {
        id: 'wildsalmon_sweetpotato_broccoli',
        name: 'Wildlachs mit Süßkartoffeln und Brokkoli',
        ingredients: [
            { ingredient: ingredients.wildSalmon, amount: 200 },
            { ingredient: ingredients.sweetPotato, amount: 200 },
            { ingredient: ingredients.broccoli, amount: 300 },
            { ingredient: ingredients.oliveoil, amount: 5 },
        ],
    },
};

export { PROTEIN_TARGET, CARBS_TARGET, FAT_TARGET };
